// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: banners.sql

package sqlcdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBanner = `-- name: CreateBanner :one
INSERT INTO banners (title, body, level, active, dismissible, created_by, starts_at, ends_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING banners.id, banners.title, banners.body, banners.level, banners.active, banners.dismissible, banners.created_by, banners.starts_at, banners.ends_at, banners.created_at, banners.updated_at
`

type CreateBannerParams struct {
	Title       string        `json:"title"`
	Body        string        `json:"body"`
	Level       string        `json:"level"`
	Active      bool          `json:"active"`
	Dismissible bool          `json:"dismissible"`
	CreatedBy   uuid.NullUUID `json:"created_by"`
	StartsAt    sql.NullTime  `json:"starts_at"`
	EndsAt      sql.NullTime  `json:"ends_at"`
}

func (q *Queries) CreateBanner(ctx context.Context, arg CreateBannerParams) (Banner, error) {
	row := q.db.QueryRowContext(ctx, createBanner,
		arg.Title,
		arg.Body,
		arg.Level,
		arg.Active,
		arg.Dismissible,
		arg.CreatedBy,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Banner
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Level,
		&i.Active,
		&i.Dismissible,
		&i.CreatedBy,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBanner = `-- name: DeleteBanner :exec
DELETE FROM banners
WHERE id = $1
`

func (q *Queries) DeleteBanner(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBanner, id)
	return err
}

const getBannerByID = `-- name: GetBannerByID :one
SELECT banners.id, banners.title, banners.body, banners.level, banners.active, banners.dismissible, banners.created_by, banners.starts_at, banners.ends_at, banners.created_at, banners.updated_at
FROM banners
WHERE id = $1
`

func (q *Queries) GetBannerByID(ctx context.Context, id uuid.UUID) (Banner, error) {
	row := q.db.QueryRowContext(ctx, getBannerByID, id)
	var i Banner
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Level,
		&i.Active,
		&i.Dismissible,
		&i.CreatedBy,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBanners = `-- name: ListActiveBanners :many
SELECT banners.id, banners.title, banners.body, banners.level, banners.active, banners.dismissible, banners.created_by, banners.starts_at, banners.ends_at, banners.created_at, banners.updated_at
FROM banners
WHERE active
  AND (starts_at IS NULL OR starts_at <= now())
  AND (ends_at IS NULL OR ends_at > now())
ORDER BY created_at DESC
`

func (q *Queries) ListActiveBanners(ctx context.Context) ([]Banner, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Banner{}
	for rows.Next() {
		var i Banner
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Level,
			&i.Active,
			&i.Dismissible,
			&i.CreatedBy,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBanners = `-- name: ListBanners :many
SELECT banners.id, banners.title, banners.body, banners.level, banners.active, banners.dismissible, banners.created_by, banners.starts_at, banners.ends_at, banners.created_at, banners.updated_at
FROM banners
ORDER BY created_at DESC
`

func (q *Queries) ListBanners(ctx context.Context) ([]Banner, error) {
	rows, err := q.db.QueryContext(ctx, listBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Banner{}
	for rows.Next() {
		var i Banner
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Level,
			&i.Active,
			&i.Dismissible,
			&i.CreatedBy,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBanner = `-- name: UpdateBanner :one
UPDATE banners
SET title = $2,
    body = $3,
    level = $4,
    active = $5,
    dismissible = $6,
    starts_at = $7,
    ends_at = $8,
    updated_at = now()
WHERE id = $1
RETURNING banners.id, banners.title, banners.body, banners.level, banners.active, banners.dismissible, banners.created_by, banners.starts_at, banners.ends_at, banners.created_at, banners.updated_at
`

type UpdateBannerParams struct {
	ID          uuid.UUID    `json:"id"`
	Title       string       `json:"title"`
	Body        string       `json:"body"`
	Level       string       `json:"level"`
	Active      bool         `json:"active"`
	Dismissible bool         `json:"dismissible"`
	StartsAt    sql.NullTime `json:"starts_at"`
	EndsAt      sql.NullTime `json:"ends_at"`
}

func (q *Queries) UpdateBanner(ctx context.Context, arg UpdateBannerParams) (Banner, error) {
	row := q.db.QueryRowContext(ctx, updateBanner,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Level,
		arg.Active,
		arg.Dismissible,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Banner
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Level,
		&i.Active,
		&i.Dismissible,
		&i.CreatedBy,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
