// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AgentAuthToken struct {
	ID         uuid.UUID    `json:"id"`
	TokenHash  string       `json:"token_hash"`
	Label      string       `json:"label"`
	CreatedAt  sql.NullTime `json:"created_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
}

type AgentCommand struct {
	ID          string                `json:"id"`
	Type        string                `json:"type"`
	NodeAgentID string                `json:"node_agent_id"`
	ContainerID sql.NullString        `json:"container_id"`
	Payload     pqtype.NullRawMessage `json:"payload"`
	Status      sql.NullString        `json:"status"`
	Result      sql.NullString        `json:"result"`
	Error       sql.NullString        `json:"error"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
	CompletedAt sql.NullTime          `json:"completed_at"`
}

type AgentHeartbeat struct {
	ID             string          `json:"id"`
	NodeAgentID    string          `json:"node_agent_id"`
	Timestamp      time.Time       `json:"timestamp"`
	Status         string          `json:"status"`
	Resources      json.RawMessage `json:"resources"`
	ContainerCount int32           `json:"container_count"`
	SystemLoad     json.RawMessage `json:"system_load"`
	Uptime         int64           `json:"uptime"`
	Version        string          `json:"version"`
	CreatedAt      time.Time       `json:"created_at"`
}

type ContainerInstance struct {
	ID            string                `json:"id"`
	Name          string                `json:"name"`
	Image         string                `json:"image"`
	ProjectID     string                `json:"project_id"`
	ServiceID     string                `json:"service_id"`
	NodeAgentID   string                `json:"node_agent_id"`
	Status        pqtype.NullRawMessage `json:"status"`
	Resources     pqtype.NullRawMessage `json:"resources"`
	Ports         pqtype.NullRawMessage `json:"ports"`
	Environment   pqtype.NullRawMessage `json:"environment"`
	Volumes       pqtype.NullRawMessage `json:"volumes"`
	Networks      pqtype.NullRawMessage `json:"networks"`
	RestartPolicy pqtype.NullRawMessage `json:"restart_policy"`
	HealthCheck   pqtype.NullRawMessage `json:"health_check"`
	CreatedAt     sql.NullTime          `json:"created_at"`
	StartedAt     sql.NullTime          `json:"started_at"`
	UpdatedAt     sql.NullTime          `json:"updated_at"`
}

type DatabaseBackup struct {
	ID          string         `json:"id"`
	DatabaseID  string         `json:"database_id"`
	Size        string         `json:"size"`
	Status      string         `json:"status"`
	BackupPath  sql.NullString `json:"backup_path"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

type DatabaseService struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	Name          string         `json:"name"`
	Type          string         `json:"type"`
	Status        string         `json:"status"`
	Version       string         `json:"version"`
	Plan          string         `json:"plan"`
	Region        string         `json:"region"`
	ConnectionUrl sql.NullString `json:"connection_url"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Deployment struct {
	ID        uuid.UUID      `json:"id"`
	ServiceID uuid.UUID      `json:"service_id"`
	Status    sql.NullString `json:"status"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Environment struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	ProjectID uuid.UUID    `json:"project_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type EnvironmentVariable struct {
	ID        uuid.UUID    `json:"id"`
	ServiceID uuid.UUID    `json:"service_id"`
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	IsSecret  sql.NullBool `json:"is_secret"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type NodeAgent struct {
	ID            string                `json:"id"`
	Name          string                `json:"name"`
	Hostname      string                `json:"hostname"`
	IpAddress     string                `json:"ip_address"`
	Port          int32                 `json:"port"`
	Status        sql.NullString        `json:"status"`
	Version       sql.NullString        `json:"version"`
	Capabilities  pqtype.NullRawMessage `json:"capabilities"`
	Resources     pqtype.NullRawMessage `json:"resources"`
	LastHeartbeat sql.NullTime          `json:"last_heartbeat"`
	CreatedAt     sql.NullTime          `json:"created_at"`
	UpdatedAt     sql.NullTime          `json:"updated_at"`
	Metadata      pqtype.NullRawMessage `json:"metadata"`
}

type Project struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ProjectMember struct {
	ID        uuid.UUID    `json:"id"`
	ProjectID uuid.UUID    `json:"project_id"`
	UserID    uuid.UUID    `json:"user_id"`
	Role      string       `json:"role"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Service struct {
	ID             uuid.UUID      `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	ProjectID      uuid.UUID      `json:"project_id"`
	EnvironmentID  uuid.UUID      `json:"environment_id"`
	ServiceType    string         `json:"service_type"`
	SourceType     string         `json:"source_type"`
	SourceUrl      sql.NullString `json:"source_url"`
	ImageName      sql.NullString `json:"image_name"`
	BuildCommand   sql.NullString `json:"build_command"`
	StartCommand   sql.NullString `json:"start_command"`
	CpuLimit       sql.NullInt32  `json:"cpu_limit"`
	MemoryLimit    sql.NullInt32  `json:"memory_limit"`
	PublicUrl      sql.NullString `json:"public_url"`
	HealthCheckUrl sql.NullString `json:"health_check_url"`
	Status         sql.NullString `json:"status"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	Type           sql.NullString `json:"type"`
	Image          sql.NullString `json:"image"`
	Command        sql.NullString `json:"command"`
	Environment    sql.NullString `json:"environment"`
	GitRepo        sql.NullString `json:"git_repo"`
	GitBranch      sql.NullString `json:"git_branch"`
	BuildPath      sql.NullString `json:"build_path"`
	Cpu            sql.NullString `json:"cpu"`
	Memory         sql.NullString `json:"memory"`
}

type ServiceTemplate struct {
	ID          string                `json:"id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	Category    string                `json:"category"`
	Logo        sql.NullString        `json:"logo"`
	Config      json.RawMessage       `json:"config"`
	Variables   pqtype.NullRawMessage `json:"variables"`
	IsOfficial  sql.NullBool          `json:"is_official"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
}
