// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompleteCommand(ctx context.Context, arg CompleteCommandParams) (AgentCommand, error)
	CountDatabaseServicesByUserAndName(ctx context.Context, arg CountDatabaseServicesByUserAndNameParams) (int64, error)
	CountProjectsByUser(ctx context.Context, arg CountProjectsByUserParams) (int64, error)
	CountServicesByProjectAndName(ctx context.Context, arg CountServicesByProjectAndNameParams) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (NodeAgent, error)
	CreateAgentAuthToken(ctx context.Context, arg CreateAgentAuthTokenParams) (AgentAuthToken, error)
	CreateCommand(ctx context.Context, arg CreateCommandParams) (AgentCommand, error)
	CreateContainer(ctx context.Context, arg CreateContainerParams) (ContainerInstance, error)
	CreateDatabaseBackup(ctx context.Context, arg CreateDatabaseBackupParams) error
	CreateDatabaseService(ctx context.Context, arg CreateDatabaseServiceParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateServiceFromTemplate(ctx context.Context, arg CreateServiceFromTemplateParams) error
	DatabaseServiceExistsByIDAndUser(ctx context.Context, arg DatabaseServiceExistsByIDAndUserParams) (bool, error)
	DeleteAgent(ctx context.Context, id string) error
	DeleteDatabaseServiceByIDAndUser(ctx context.Context, arg DeleteDatabaseServiceByIDAndUserParams) error
	DeleteProjectByID(ctx context.Context, projectID uuid.UUID) (int64, error)
	GetActiveAgentAuthTokenByHash(ctx context.Context, tokenHash string) (AgentAuthToken, error)
	GetAgent(ctx context.Context, id string) (NodeAgent, error)
	GetAgentByHostAndIP(ctx context.Context, arg GetAgentByHostAndIPParams) (NodeAgent, error)
	GetCommandForAgent(ctx context.Context, arg GetCommandForAgentParams) (AgentCommand, error)
	GetContainer(ctx context.Context, id string) (ContainerInstance, error)
	GetContainerForAgent(ctx context.Context, arg GetContainerForAgentParams) (ContainerInstance, error)
	GetDatabaseBackupByIDAndDatabaseAndUser(ctx context.Context, arg GetDatabaseBackupByIDAndDatabaseAndUserParams) (DatabaseBackup, error)
	GetDatabaseServiceByIDAndUser(ctx context.Context, arg GetDatabaseServiceByIDAndUserParams) (GetDatabaseServiceByIDAndUserRow, error)
	GetProjectByIDForUser(ctx context.Context, arg GetProjectByIDForUserParams) (Project, error)
	GetProjectOwnerByID(ctx context.Context, projectID uuid.UUID) (uuid.UUID, error)
	GetProjectOwnerID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetProjectRoleForUser(ctx context.Context, arg GetProjectRoleForUserParams) (string, error)
	GetServiceTemplateByID(ctx context.Context, id string) (ServiceTemplate, error)
	InsertAgentHeartbeat(ctx context.Context, arg InsertAgentHeartbeatParams) error
	InsertProjectEnvironment(ctx context.Context, arg InsertProjectEnvironmentParams) error
	ListAgentAuthTokens(ctx context.Context) ([]AgentAuthToken, error)
	ListAgentHeartbeatsSince(ctx context.Context, arg ListAgentHeartbeatsSinceParams) ([]AgentHeartbeat, error)
	ListAgents(ctx context.Context) ([]NodeAgent, error)
	ListCommandsForAgent(ctx context.Context, nodeAgentID string) ([]AgentCommand, error)
	ListContainersForAgent(ctx context.Context, nodeAgentID string) ([]ContainerInstance, error)
	ListDatabaseBackupsByDatabaseAndUser(ctx context.Context, arg ListDatabaseBackupsByDatabaseAndUserParams) ([]DatabaseBackup, error)
	ListDatabaseServicesByUser(ctx context.Context, userID string) ([]ListDatabaseServicesByUserRow, error)
	ListDueDatabaseBackups(ctx context.Context) ([]ListDueDatabaseBackupsRow, error)
	ListPendingCommands(ctx context.Context, nodeAgentID string) ([]AgentCommand, error)
	ListProjectsWithStatsByUser(ctx context.Context, arg ListProjectsWithStatsByUserParams) ([]ListProjectsWithStatsByUserRow, error)
	ListServiceTemplates(ctx context.Context) ([]ServiceTemplate, error)
	ListServiceTemplatesByCategory(ctx context.Context, category string) ([]ServiceTemplate, error)
	RevokeAgentAuthToken(ctx context.Context, id uuid.UUID) (AgentAuthToken, error)
	SetDatabaseBackupScheduleByIDAndUser(ctx context.Context, arg SetDatabaseBackupScheduleByIDAndUserParams) error
	SetDatabaseBackupStatusByID(ctx context.Context, arg SetDatabaseBackupStatusByIDParams) error
	SetDatabaseNextBackupAt(ctx context.Context, arg SetDatabaseNextBackupAtParams) error
	SetDatabaseServiceStatusAndConnectionByID(ctx context.Context, arg SetDatabaseServiceStatusAndConnectionByIDParams) error
	SetDatabaseServiceStatusByID(ctx context.Context, arg SetDatabaseServiceStatusByIDParams) error
	SetDatabaseServiceStatusByIDAndUser(ctx context.Context, arg SetDatabaseServiceStatusByIDAndUserParams) error
	TouchAgentAuthToken(ctx context.Context, tokenHash string) error
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (NodeAgent, error)
	UpdateAgentHeartbeat(ctx context.Context, arg UpdateAgentHeartbeatParams) error
	UpdateContainerStatus(ctx context.Context, arg UpdateContainerStatusParams) error
	UpdateDatabaseServiceNameAndPlanByIDAndUser(ctx context.Context, arg UpdateDatabaseServiceNameAndPlanByIDAndUserParams) error
	UpdateDatabaseServiceNameByIDAndUser(ctx context.Context, arg UpdateDatabaseServiceNameByIDAndUserParams) error
	UpdateDatabaseServicePlanByIDAndUser(ctx context.Context, arg UpdateDatabaseServicePlanByIDAndUserParams) error
	UpdateProjectByID(ctx context.Context, arg UpdateProjectByIDParams) (int64, error)
	UpsertEnvironmentVariable(ctx context.Context, arg UpsertEnvironmentVariableParams) error
}

var _ Querier = (*Queries)(nil)
